# Generated by Django 4.2.7 on 2025-12-23 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DetectionStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("total_detections", models.IntegerField(default=0)),
                ("hindi_count", models.IntegerField(default=0)),
                ("english_count", models.IntegerField(default=0)),
                ("hinglish_count", models.IntegerField(default=0)),
                ("unknown_count", models.IntegerField(default=0)),
                ("avg_confidence", models.FloatField(default=0.0)),
            ],
            options={
                "verbose_name": "Detection Statistics",
                "verbose_name_plural": "Detection Statistics",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="HinglishWord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word", models.CharField(max_length=100, unique=True)),
                (
                    "word_type",
                    models.CharField(
                        choices=[
                            ("verb", "Verb"),
                            ("noun", "Noun"),
                            ("adjective", "Adjective"),
                            ("particle", "Particle"),
                            ("expression", "Expression"),
                        ],
                        max_length=20,
                    ),
                ),
                ("frequency", models.IntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Hinglish Word",
                "verbose_name_plural": "Hinglish Words",
                "ordering": ["-frequency", "word"],
            },
        ),
        migrations.CreateModel(
            name="LanguageDetection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("input_text", models.TextField()),
                (
                    "detected_language",
                    models.CharField(
                        choices=[
                            ("Hindi", "Hindi"),
                            ("English", "English"),
                            ("Hinglish", "Hinglish"),
                            ("Unknown", "Unknown"),
                        ],
                        max_length=20,
                    ),
                ),
                ("confidence", models.FloatField()),
                ("hindi_score", models.FloatField(default=0.0)),
                ("english_score", models.FloatField(default=0.0)),
                ("hinglish_score", models.FloatField(default=0.0)),
                ("hindi_percentage", models.FloatField(default=0.0)),
                ("english_percentage", models.FloatField(default=0.0)),
                ("hinglish_percentage", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Language Detection",
                "verbose_name_plural": "Language Detections",
                "ordering": ["-created_at"],
            },
        ),
    ]
